name: '@lapacazo'
favicon: null
layout_spectrum: 0.50501
typography_spectrum: 0.76179
title: '@lapacazo-What Do You Know?'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8c942'
    - '#d92959'
    - '#000000'
    - '#eb88a2'
  brandStrength: 0.8912244976963848
  lightness: 0.9293584108818322
  saturation: 0.458266006084159
  rhythmicContrast: 0.538402694510296
purpose: []
