name: '@lapacazo'
favicon: null
layout_spectrum: 0.35745
typography_spectrum: 1
title: '@lapacazo-What Do You Know?'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe98e7'
    - '#e2dddf'
    - '#9f7998'
    - '#1d1d20'
    - '#abcf44'
  brandStrength: 0.8912244976963848
  lightness: 0.9293584108818322
  saturation: 0.458266006084159
  rhythmicContrast: 0.538402694510296
purpose: []
