name: '@lapacazo'
favicon: null
layout_spectrum: 0.11768797738477588
typography_spectrum: 0.8399860509671271
title: '@lapacazo-What Do You Know?'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8912244976963848
  lightness: 0.9293584108818322
  saturation: 0.458266006084159
  rhythmicContrast: 0.538402694510296
purpose: []
